In [2]:
print("hello world")
True and False

hello world


False

In [7]:
x = 500
for x in range(0,100):
    1

In [15]:
print(13 not in range (12,16))
print(17 in range (12,16))

False
False


In [11]:
print(5|9)

13


In [13]:
x=2
print(x**5)

32


In [17]:
income = 100000
incertives = 10000
total_income = income + incertives
print(total_income)

110000


In [18]:
income = 100000
incertives = 12550.50
total_income = income +incertives
print(total_income)

112550.5


In [20]:
ketty_age = 28
kenny_age = 25

In [21]:
ketty_age == kenny_age

False

In [ ]:
ketty_age <= kenny_age


True

In [25]:
ketty_age >= kenny_age


True

In [24]:
ketty_age < kenny_age


False

In [23]:
ketty_age > kenny_age

True

In [26]:
is_student = True
in_college = True
in_school = False

In [28]:
is_student and in_college

True

In [29]:
is_student or in_school

True

In [1]:
number = 10
(number % 2 == 0) & (number % 3 == 0)

False

In [2]:
number = 10
(number % 2 == 0) | (number % 3 == 0)

True

In [ ]:
num = 8
if(num > 2):
    print(num, "is greater than zero")
print("this is always printed")

8 is greater than zero
thisis always printed


In [8]:
num = -1
if(num > 0):
    print(num, "is greater than zero")
print("this is always printed")

this is always printed


In [2]:
num =-1
if(num > 0):
    print(num, "is greter than zero")
else:
    print(num, "is less than zero")
print("This is always printed")

-1 is less than zero
This is always printed


In [4]:
age = int(input("enter age: "))
if(0 < age < 3):
    print("no fares for age group 0-3")
elif(3 < age < 10):
    print("bus fare is 20")
elif(10 < age < 20):
    print("bus fare is 25")
else:
    print("bus fare is 30")

no fares for age group 0-3


In [12]:
num1 = 10
num2 = 30
num3 = 55
if (num1 > num2):
    print(num1, "is greater")
else:
    if (num3 > num2):
        print(num3, "is greater")
    else:
        print(num2, "is greater")

55 is greater


In [16]:
a = int(input("enter first no. :"))
b = int(input("enter seconf no. :"))
c = int(input("enter third no. :"))

if a >= b:
    if a>= c:
        greatest = a
    else:
        greatest = c
else:
    if b >= c:
        greatest = b
    else:
        greatest = c
print("the greatest no. is", greatest)

the greatest no. is 18


In [17]:
num = 10
addition = 0
i = 1
while(i <= num):
    addition = addition + i
    i = i + 1
print("addition is: ", addition)

addition is:  55


In [18]:
number = range(1, 11)
addition = 0
for i in number:
    addition = addition + i
print("addition is : ", addition)

addition is :  55


In [1]:
text = "Knowledge Hut"
for letter in text:
    if letter == ' ':
        print("The loop skipped a space here")
        continue
    print(letter)

K
n
o
w
l
e
d
g
e
The loop skipped a space here
H
u
t


In [3]:
levels = int(input("enter no. of levels: "))
for level in range(1, levels+1):
    for num in range(level):
        print(level, end=" ")
print("\n")

1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 



In [4]:
name = input("enter your name: ")
print("Hii", name)

Hii SamZ


In [5]:
def greet(name):
    print("Hello", name)
greet("SamZ")

Hello SamZ


In [14]:
#write a function to calculate and return sum of the nos.
def sum(x, y):
    z = x + y
    # return z
result = sum(5, 7)
# print(result)
# print(sum(5,6))
# print(z)

In [25]:
#create a function that return both area and circumference of a circle given its radidus
PI = 3.14
def circle(a):
    print("the area of circle is", a,"is", PI * a**2)
    print("the circumference of circle is", a, "is", 2*PI*a)
circle(2)

the area of circle is 2 is 12.56
the circumference of circle is 2 is 12.56


In [ ]:
#write a function that greet a user if no name is provided it shoukd greet with default name
def defFunction(name = "SamZ"):
    print("my name", name)
defFunction("Python")
defFunction()

my name 
my name SamZ


In [28]:
#lambda function 
sq = lambda x : x**2
print(sq(2))

4


In [1]:
def sum_all(*args):
    return sum(args)
print(sum_all(1,2,3,4))
# print(sum_all(1,2,3,4,5,6,7))


10


In [2]:
def func(*args):
    sum = 0
    for i in args:
        sum += i
    print(sum)
func(1,2,3,4,5,6,7,8,9)

45


In [ ]:
#create a funtion that accept any no. of keyword arguments and print them in the form of key=value
def print_kwargs(**kwargs):
    for key,value in kwargs.items():
        print(f"{key}={value}")
print_kwargs(name = "SamZ", age = 21, city= "BBSR")


name=SamZ
age=21
city=BBSR


In [13]:
def recurr(n):
    if(n==1 or n==0):
        return 1
    else:
        return n*recurr(n-1)
recurr(4)

24

In [3]:
#write a function to check if a no. is prime
def prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % 2 == 0:
            return False
        return True
num = int(input("enter a no. "))
if prime(num):
    print(f"{num} is a prime no.")
else:
    print(f"{num} is not a Prime no. ")

2 is not a Prime no. 


In [8]:
#create a function to calculate the area of a rectangle
def retangle(l, b):
    return l * b
l = int(input(f"enter the length : "))
b = int(input(f"enter the breadth : "))
area = retangle(l, b)
print(f"the area of the rectangle is {area}")

the area of the rectangle is 8


In [11]:
#craete a function to find the maximum of three nos.
def max(a, b, c):
    if(a >= b and a >= c):
        return a
    elif(b >= a and b >= c):
        return b
    else:
        return c
max(1,4,2)

4

In [13]:
username = "John"
def function():
    username = "sumit"
function()
print(username)

John


In [ ]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

    def my_brand(self):
        print(f"brand of the car is : {self.brand}")

    def my_model(self):
        print(f"model of the car is : {self.model}")
my_new_car = Car("Ford", "Mustang")
my_new_car.my_brand()
my_new_car.my_model() 


brand of the car is : Ford
model of the car is : Mustang


In [ ]:
class Electric_Car:
    def __init_(self,charge):
        self.charge = charge
        super().__init__(brand, model)
    def showCharge(self):
        print(f"charge of the car is : {self.charge}")
my_new_car = Electric_Car(60)
my_new_car.showCharge()
 

TypeError: Electric_Car() takes no arguments

In [8]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:
import numpy as np 
arr =  np.array([[[1,2,3],[4,5,6],[6,7,8]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [6 7 8]]]


In [22]:
py_list = [1,2,3]
print("python list multiplication", py_list)
np_array = np.array = [1,2,3]
print("np array multiplication: ", np_array * 2)

python list multiplication [1, 2, 3]
np array multiplication:  [1, 2, 3, 1, 2, 3]


In [23]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
arr = np.linspace(0, 100, 6)
print(arr)

[  0.  20.  40.  60.  80. 100.]


In [45]:
arr = np.arange(0, 10, 3)
print(arr)

[0 3 6 9]


In [46]:
arr = np.full((2, 3), 8)
print(arr)

[[8 8 8]
 [8 8 8]]


In [3]:
arr = np.random.rand(4,5)
print(arr)

[[0.6901364  0.67903278 0.00578619 0.93624561 0.9930718 ]
 [0.81536259 0.66300546 0.12174094 0.2070931  0.51965195]
 [0.65264734 0.69031457 0.01040525 0.84275706 0.25595354]
 [0.45979044 0.52602681 0.42040973 0.56046924 0.99982505]]


In [26]:
arr = np.random.rand(6, 7) * 100
print(arr)

[[11.69561074 70.99044238 43.04279982 50.01999645 72.55476548 44.48386232
  34.22821074]
 [26.43376304 52.63799201 61.86114184 10.68085284  7.56020138 86.56239638
  57.61028571]
 [69.23516493 93.06538055 52.02802783 20.3405143  80.196836   89.97633022
  21.95321499]
 [55.92159844  6.82526532 79.91718258 68.11963838 13.69437651 31.36119482
   7.31722592]
 [51.82732651 52.20463065 98.94110658 62.65433763  6.90274197 11.31170981
  57.79494302]
 [14.90101136 31.68864952 81.35718134 18.48750076 66.60698477 18.88304243
  82.3939944 ]]


In [19]:
arr = np.random.randint(5, size = (1, 3))
print(arr) 

[[2 2 0]]


In [18]:
arr.astype(bool)

array([], shape=(0, 2), dtype=bool)

In [17]:
arr.tolist()

[]

In [3]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None,
     like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If 

In [4]:
arr.size

9

In [5]:
arr.shape

(1, 3, 3)

In [20]:
arr = np.random.rand(0, 2)
arr.dtype

dtype('float64')

In [22]:
arr.view(int)

array([], shape=(0, 2), dtype=int64)

In [32]:
arr = np.random.rand(2, 6)

arr1=sorted(arr)
print(arr1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [38]:
arr = np.array([(1,2,3),(4,5,6)])
print(arr)
arr.flatten()

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [39]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
arr = np.array([1,2,3,4,5,6])
arr.reshape(3,4)
print(arr)

NameError: name 'np' is not defined

In [ ]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
np.append(arr, 2)

array([1, 2, 3, 2])

In [7]:
np.insert(arr, 2, 5)

array([1, 2, 5, 3])

In [42]:
print(arr)

[1 2 3]


In [16]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2 = np.array([[7,8,9],[10,11,12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [40]:
np.concatenate((arr1, arr2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [26]:
np.split(arr, 3)

[array([1]), array([2]), array([3])]

In [34]:
np.hsplit(arr, 3)

[array([1]), array([2]), array([3])]

In [48]:
arr[1]

np.int64(2)

In [53]:
arr1[0,2]

np.int64(3)

In [56]:
arr[1]=4
print(arr)

[1 4 3]


In [64]:
arr[1:5]

array([4, 3])

In [67]:
arr1[0:3, 2]

array([3, 6])

In [71]:
arr[:77]

array([1, 4, 3])

In [83]:
arr1[0,:]

array([1, 2, 3])

In [91]:
arr<4

array([ True, False,  True])

In [93]:
(arr1<3) & (arr2>5)

array([[ True,  True, False],
       [False, False, False]])

In [97]:
~arr
print(~arr)

[-2 -5 -4]


In [100]:
arr[arr<2]

array([1])

In [105]:
(arr1<2) | (arr2>40)

array([[ True, False, False],
       [False, False, False]])

In [107]:
np.add(arr, 4)

array([5, 8, 7])

In [109]:
np.subtract(arr, 3)

array([-2,  1,  0])

In [111]:
np.multiply(arr, 3)

array([ 3, 12,  9])

In [113]:
np.divide(arr, 4)

array([0.25, 1.  , 0.75])

In [117]:
np.power(arr, 5)

array([   1, 1024,  243])

In [119]:
np.add(arr1, arr2)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [121]:
np.subtract(arr1,arr2)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [123]:
np.multiply(arr1,arr2)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [125]:
np.divide(arr1,arr2)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [126]:
np.power(arr1,arr2)

array([[         1,        256,      19683],
       [   1048576,   48828125, 2176782336]])

In [128]:
np.array_equal(arr1,arr2)

False

In [131]:
np.sqrt(arr)

array([1.        , 2.        , 1.73205081])

In [133]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.14112001])

In [136]:
np.abs(arr)

array([1, 4, 3])

In [137]:
np.ceil(arr)

array([1, 4, 3])

In [139]:
np.floor(arr)

array([1, 4, 3])

In [146]:
np.mean(arr)

np.float64(2.6666666666666665)

In [149]:
arr.sum()

np.int64(8)

In [151]:
arr.min()

np.int64(1)

In [153]:
arr.max()

np.int64(4)

In [159]:
np.var(arr, axis=0)

np.float64(1.5555555555555556)

In [161]:
np.std(arr)

np.float64(1.247219128924647)

In [ ]:
arr.corrcoef()

AttributeError: 'numpy.ndarray' object has no attribute 'corrcoef'